//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NationalCrime.Web.NationalCrimeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalCrimeService.INationalCrimeService")]
    public interface INationalCrimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCrimeService/ValidateLogin", ReplyAction="http://tempuri.org/INationalCrimeService/ValidateLoginResponse")]
        bool ValidateLogin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCrimeService/Register", ReplyAction="http://tempuri.org/INationalCrimeService/RegisterResponse")]
        string Register(string username, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationalCrimeService/SearchCriminal", ReplyAction="http://tempuri.org/INationalCrimeService/SearchCriminalResponse")]
        int SearchCriminal(string name, string nationality, string gender, float startheight, float endheight, float startweight, float endweight, int startage, int endage, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalCrimeServiceChannel : NationalCrime.Web.NationalCrimeService.INationalCrimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalCrimeServiceClient : System.ServiceModel.ClientBase<NationalCrime.Web.NationalCrimeService.INationalCrimeService>, NationalCrime.Web.NationalCrimeService.INationalCrimeService {
        
        public NationalCrimeServiceClient() {
        }
        
        public NationalCrimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalCrimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCrimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalCrimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidateLogin(string username, string password) {
            return base.Channel.ValidateLogin(username, password);
        }
        
        public string Register(string username, string email, string password) {
            return base.Channel.Register(username, email, password);
        }
        
        public int SearchCriminal(string name, string nationality, string gender, float startheight, float endheight, float startweight, float endweight, int startage, int endage, string email) {
            return base.Channel.SearchCriminal(name, nationality, gender, startheight, endheight, startweight, endweight, startage, endage, email);
        }
    }
}
